#!/usr/bin/env python
import os
import sys
import json

STASH_FILE = '.stash'

def __stash_file_path():
    return os.path.expanduser(os.path.join('~', STASH_FILE))

def __ensure_stash_file_exists():
    if not os.path.exists(__stash_file_path()):
        with open(__stash_file_path(), 'w') as f:
            f.write('{}')

def stash(filename):
    __ensure_stash_file_exists()
    filename = os.path.abspath(filename)

    if not os.path.exists(filename):
        sys.stderr.write('File not found: %s\n' % filename)
        return 1

    with open(__stash_file_path(), 'r+') as f:
        try:
            data = json.load(f)
        except ValueError:
            sys.stderr.write('Stash file corrupted. Delete this file to continue: %s\n' % __stash_file_path())
            return 1

        print 'Adding file as last item:', filename
        if 'files' not in data:
            data['files'] = []
        data['files'].append(filename)
        f.seek(0)
        json.dump(data, f, sort_keys=True, indent=4, separators=(',', ': '))
        f.truncate()
    return 0

if __name__ == '__main__':
    sys.exit(stash(sys.argv[1]))

